# Map arkimet's json format to the one expected by the API
NAME_MAPS: dict[str, dict[str, str]] = {
    "origin": {
        "style": "s",
        "centre": "ce",
        "subcentre": "sc",
        "desc": "desc",
        "process": "pr",
        "process_type": "pt",
        "background_process_id": "bi",
        "process_id": "pi",
        "wmo": "wmo",
        "rad": "rad",
        "plc": "plc",
    },
    "product": {
        "style": "s",
        "origin": "or",
        "table": "ta",
        "product": "pr",
        "centre": "ce",
        "discipline": "di",
        "category": "ca",
        "number": "no",
        "table_version": "tv",
        "local_table_version": "ltv",
        "type": "ty",
        "subtype": "st",
        "local_subtype": "ls",
        "value": "va",
        "object": "ob",
        "id": "id",
    },
    "level": {
        "style": "s",
        "type": "lt",
        "scale": "sc",
        "scale1": "s1",
        "scale2": "s2",
        "value": "va",
        "value1": "v1",
        "value2": "v2",
        "l1": "l1",
        "l2": "l2",
        "min": "mi",
        "max": "ma",
    },
    "timerange": {
        "style": "s",
        "type": "ty",
        "unit": "un",
        "p1": "p1",
        "p2": "p2",
        "value": "va",
        "step_len": "sl",
        "step_unit": "su",
        "stat_type": "pt",
        "stat_len": "pl",
        "stat_unit": "pu",
    },
    "area": {
        "style": "s",
        "id": "id",
        "value": "va",
    },
    "proddef": {
        "style": "s",
        "value": "va",
    },
    "run": {
        "style": "s",
        "value": "va",
    },
}
